auth-server-url: http://localhost:8080 # 授权服务地址
server:
  port: 8088
spring:
  security:
    oauth2:
      client:
        provider:
          token-uri: http://localhost:8080/oauth/token
          authorization-uri: http://localhost:8080/oauth/authorize
          user-info-uri: http://localhost:8080/oauth/check_token #检查令牌
        registration:
          client-id: client1
          client-secret: 123456
          scope: test
#logging:
#  level:
#    root: DEBUG

#auth-server: http://localhost:8080 # 认证服务器地址
#server:
#  port: 8088
#security:
#  oauth2:
#    client:
#      client-id: testclient # 授权服务器配置的client id
#      client-secret: testclient # 授权服务器配置的client secret
#      scope: test
#      access-token-uri: ${auth-server}/oauth/token # 获取access token接口
#      user-authorization-uri: ${auth-server}/oauth/authorize #  获取Authorization Code接口
#    resource:
#      token-info-uri: ${auth-server}/oauth/check_token # 验证token的接口
